#!/bin/bash
case "$1" in
  config)
    cat <<CONFIG
Loading from configuration file /srv/chef/.chef/knife.rb
client_key: /srv/chef/.chef/admin.pem
CONFIG
    ;;
  cookbook)
    echo 'lrqdo_docker   0.2.12  0.2.11  0.2.10  0.2.9  0.2.8  0.2.6  0.2.5'
    ;;
  *)
    echo "knife mock does not know how to '$1'"
    exit 1
    ;;
esac
